define([
    'coreUtils/core/htmlParser',
    'coreUtils/core/htmlTransformer',
    'coreUtils/core/textSecurityFixer',
    'coreUtils/core/throttleUtils',
    'coreUtils/core/keyboardUtils',
    'coreUtils/core/classNames',
    'coreUtils/core/cookieUtils',
    'coreUtils/core/imageUtils',
    'coreUtils/core/ajaxLibrary',
    'coreUtils/core/tween',
    'coreUtils/core/urlUtils',
    'coreUtils/core/store2',
    'coreUtils/core/mobileViewportFixer',
    'coreUtils/core/dataUtils',
    'coreUtils/core/dateTimeUtils',
    'coreUtils/core/validationUtils',
    'coreUtils/core/cssUtils',
    'coreUtils/core/hashUtils',
    'coreUtils/core/guidUtils',
    'coreUtils/core/arrayUtils',
    'coreUtils/core/stringUtils',
    'coreUtils/core/mediaZoomCalculations',
    'coreUtils/core/objectUtils',
    'coreUtils/core/animationFrame',
    'coreUtils/core/scrollAnchorsUtils',
    'coreUtils/core/domMeasurements',
    'coreUtils/core/storage',
    'coreUtils/core/style',
    'coreUtils/core/verticalMenuCalculations',
    'coreUtils/core/galleriesCommonLayout',
    'coreUtils/core/requestsUtil',
    'coreUtils/core/boundingLayout',
    'coreUtils/core/nonPageItemZoom',
    'coreUtils/core/colorParser',
    'coreUtils/core/reactComponentUtils',
    'coreUtils/core/appPartMediaInnerViewNameUtils',
    'coreUtils/core/dockUtils',
    'coreUtils/core/viewportUtils',
    'coreUtils/core/containerBackgroundUtils',
    'coreUtils/core/math',
    'coreUtils/core/functionUtils',
    'coreUtils/core/balataConsts',
    'coreUtils/core/blogAppPartNames',
    'coreUtils/core/wixUserApi',
    'coreUtils/core/languages',
    'coreUtils/core/siteConstants',
    'coreUtils/core/textPatternRecognizer',
    'coreUtils/core/anchorTagsGenerator',
    'coreUtils/core/routersBackEndRequests',
    'coreUtils/core/errorPages',
    'coreUtils/core/logWixCodeConsoleMessage',
    'coreUtils/core/fragment'

], function (htmlParser,
             htmlTransformer,
             textSecurityFixer,
             throttleUtils,
             keyboardUtils,
             classNames,
             cookieUtils,
             imageUtils,
             ajaxLibrary,
             tween,
             urlUtils,
             store,
             mobileViewportFixer,
             dataUtils,
             dateTimeUtils,
             validationUtils,
             cssUtils,
             hashUtils,
             guidUtils,
             arrayUtils,
             stringUtils,
             mediaZoomCalculations,
             objectUtils,
             animationFrame,
             scrollAnchorsUtils,
             domMeasurements,
             storage,
             style,
             verticalMenuCalculations,
             galleriesCommonLayout,
             requestsUtil,
             boundingLayout,
             nonPageItemZoom,
             colorParser,
             reactComponentUtils,
             appPartMediaInnerViewNameUtils,
             dockUtils,
             viewportUtils,
             containerBackgroundUtils,
             math,
             functionUtils,
             balataConsts,
             blogAppPartNames,
             wixUserApi,
             languages,
             siteConstants,
             textPatternRecognizer,
             anchorTagsGenerator,
             routersBackEndRequests,
             errorPages,
             logWixCodeConsoleMessage,
             fragment) {
    'use strict';

    /**
     * @exports coreUtils
     */
    var exports = {
        htmlTransformer: htmlTransformer,
        textSecurityFixer: textSecurityFixer,
        htmlParser: htmlParser,
        throttleUtils: throttleUtils,
        keyboardUtils: keyboardUtils,
        classNames: classNames,
        cookieUtils: cookieUtils,
        imageUtils: imageUtils,
        tween: tween,
        urlUtils: urlUtils,
        routersBackEndRequests:routersBackEndRequests,
        Store: store,
        mobileViewportFixer: mobileViewportFixer,
        dataUtils: dataUtils,
        dateTimeUtils: dateTimeUtils,
        validationUtils: validationUtils,
        ajaxLibrary: ajaxLibrary,
        cssUtils: cssUtils,
        hashUtils: hashUtils,
        guidUtils: guidUtils,
        arrayUtils: arrayUtils,
        stringUtils: stringUtils,
        mediaZoomCalculations: mediaZoomCalculations,
        objectUtils: objectUtils,
        animationFrame: animationFrame,
        scrollAnchors: scrollAnchorsUtils,
        domMeasurements: domMeasurements,
        storage: storage,
        style: style,
        galleriesCommonLayout: galleriesCommonLayout,
        requestsUtil: requestsUtil,
        boundingLayout: boundingLayout,
        verticalMenuCalculations: verticalMenuCalculations,
        nonPageItemZoom: nonPageItemZoom,
        appPartMediaInnerViewNameUtils: appPartMediaInnerViewNameUtils,
        colorParser: colorParser,
        reactComponentUtils: reactComponentUtils,
        dockUtils: dockUtils,
        viewportUtils: viewportUtils,
        containerBackgroundUtils: containerBackgroundUtils,
        math: math,
        functionUtils: functionUtils,
        balataConsts: balataConsts,
        blogAppPartNames: blogAppPartNames,
        wixUserApi: wixUserApi,
        languages: languages,
        siteConstants: siteConstants,
        textPatternRecognizer: textPatternRecognizer,
        anchorTagsGenerator: anchorTagsGenerator,
        errorPages: errorPages,
        logWixCodeConsoleMessage: logWixCodeConsoleMessage,
        fragment: fragment
    };
    return exports;
});
