define([
    'documentServices/componentsMetaData/components/ebayItemsBySellerMetaData',
    'documentServices/componentsMetaData/components/verticalAnchorsMenuMetaData',
    'documentServices/componentsMetaData/components/adminLoginButtonMetaData',
    'documentServices/componentsMetaData/components/bgImageStripMetaData',
    'documentServices/componentsMetaData/components/contactFormMetaData',
    'documentServices/componentsMetaData/components/facebookLikeBoxMetaData',
    'documentServices/componentsMetaData/components/facebookLikeMetaData',
    'documentServices/componentsMetaData/components/facebookShareMetaData',
    'documentServices/componentsMetaData/components/fiveGridLineMetaData',
    'documentServices/componentsMetaData/components/flickrBadgeWidgetMetaData',
    'documentServices/componentsMetaData/components/headerMetaData',
    'documentServices/componentsMetaData/components/footerMetaData',
    'documentServices/componentsMetaData/components/imageButtonMetaData',
    'documentServices/componentsMetaData/components/itunesButtonMetaData',
    'documentServices/componentsMetaData/components/linkBarMetaData',
    'documentServices/componentsMetaData/components/onlineClockMetaData',
    'documentServices/componentsMetaData/components/pageGroupMetaData',
    'documentServices/componentsMetaData/components/pageMetaData',
    'documentServices/componentsMetaData/components/groupMetaData',
    'documentServices/componentsMetaData/components/flashComponentMetaData',
    'documentServices/componentsMetaData/components/pagesContainerMetaData',
    'documentServices/componentsMetaData/components/payPalButtonMetaData',
    'documentServices/componentsMetaData/components/pinItPinWidgetMetaData',
    'documentServices/componentsMetaData/components/pinterestFollowMetaData',
    'documentServices/componentsMetaData/components/pinterestPinItMetaData',
    'documentServices/componentsMetaData/components/rssButtonMetaData',
    'documentServices/componentsMetaData/components/screenWidthContainerMetaData',
    'documentServices/componentsMetaData/components/stripContainerMetaData',
    'documentServices/componentsMetaData/components/singleAudioPlayerMetaData',
    'documentServices/componentsMetaData/components/siteButtonMetaData',
    'documentServices/componentsMetaData/components/siteSegmentContainerMetaData',
    'documentServices/componentsMetaData/components/siteStructureMetaData',
    'documentServices/componentsMetaData/components/skypeCallButtonMetaData',
    'documentServices/componentsMetaData/components/slideShowGalleryMetaData',
    'documentServices/componentsMetaData/components/thumbnailsMetaData',
    'documentServices/componentsMetaData/components/accordionMetaData',
    'documentServices/componentsMetaData/components/googleMapMetaData',
    'documentServices/componentsMetaData/components/spotifyFollowMetaData',
    'documentServices/componentsMetaData/components/subscribeFormMetaData',
    'documentServices/componentsMetaData/components/svgShapeMetaData',
    'documentServices/componentsMetaData/components/tinyMenuMetaData',
    'documentServices/componentsMetaData/components/backToTopButtonMetaData',
    'documentServices/componentsMetaData/components/verticalLineMetaData',
    'documentServices/componentsMetaData/components/vKShareButtonMetaData',
    'documentServices/componentsMetaData/components/weatherMetaData',
    'documentServices/componentsMetaData/components/wFacebookCommentMetaData',
    'documentServices/componentsMetaData/components/disqusCommentsMetaData',
    'documentServices/componentsMetaData/components/radioGroupMetaData',
    'documentServices/componentsMetaData/components/wGooglePlusOneMetaData',
    'documentServices/componentsMetaData/components/wPhotoMetaData',
    'documentServices/componentsMetaData/components/wTwitterFollowMetaData',
    'documentServices/componentsMetaData/components/wTwitterTweetMetaData',
    'documentServices/componentsMetaData/components/youTubeSubscribeButtonMetaData',
    'documentServices/componentsMetaData/components/tpaWidgetMetaData',
    'documentServices/componentsMetaData/components/tpaGluedWidgetMetaData',
    'documentServices/componentsMetaData/components/tpaSectionMetaData',
    'documentServices/componentsMetaData/components/appPageMetaData',
    'documentServices/componentsMetaData/components/appPartMetaData',
    'documentServices/componentsMetaData/components/appPart2MetaData',
    'documentServices/componentsMetaData/components/anchorMetaData',
    'documentServices/componentsMetaData/components/masonryMetaData',
    'documentServices/componentsMetaData/components/freestyleMetaData',
    'documentServices/componentsMetaData/components/stripGallerySlideShowMetaData',
    'documentServices/componentsMetaData/components/stripShowCaseMetaData',
    'documentServices/componentsMetaData/components/collageMetaData',
    'documentServices/componentsMetaData/components/3DCarouselMetaData',
    'documentServices/componentsMetaData/components/videoMetaData',
    'documentServices/componentsMetaData/components/matrixGalleryMetaData',
    'documentServices/componentsMetaData/components/documentMediaMetaData',
    'documentServices/componentsMetaData/components/spotifyPlayerMetaData',
    'documentServices/componentsMetaData/components/soundCloudMetaData',
    'documentServices/componentsMetaData/components/wRichTextMetaData',
    'documentServices/componentsMetaData/components/verticalMenuMetaData',
    'documentServices/componentsMetaData/components/dropDownMenuMetaData',
    'documentServices/componentsMetaData/components/sliderGalleryMetaData',
    'documentServices/componentsMetaData/components/PaginatedGridGalleryMetaData',
    'documentServices/componentsMetaData/components/containerMetaData',
    'documentServices/componentsMetaData/components/popupContainerMetaData',
    'documentServices/componentsMetaData/components/audioPlayerMetaData',
    'documentServices/componentsMetaData/components/clipArtMetaData',
    'documentServices/componentsMetaData/components/boxSlideShowSlideMetaData',
    'documentServices/componentsMetaData/components/boxSlideShowMetaData',
    'documentServices/componentsMetaData/components/stripSlideShowSlideMetaData',
    'documentServices/componentsMetaData/components/stripSlideShowMetaData',
    'documentServices/componentsMetaData/components/stripColumnsMetaData',
    'documentServices/componentsMetaData/components/textInputMetadata',
    'documentServices/componentsMetaData/components/checkboxMetadata',
    'documentServices/componentsMetaData/components/datePickerMetadata',
    'documentServices/componentsMetaData/components/columnMetaData',
    'documentServices/componentsMetaData/components/controllerMetaData',
    'documentServices/componentsMetaData/components/wixappsOnlyMetaData',
    'documentServices/componentsMetaData/components/hoverboxMetaData',
    'documentServices/componentsMetaData/components/gridMetaData'
], function (ebayItemsBySellerMetaData,
             verticalAnchorsMenuMetaData,
             adminLoginButtonMetaData,
             bgImageStripMetaData,
             contactFormMetaData,
             facebookLikeBoxMetaData,
             facebookLikeMetaData,
             facebookShareMetaData,
             fiveGridLineMetaData,
             flickrBadgeWidgetMetaData,
             headerMetaData,
             footerMetaData,
             imageButtonMetaData,
             itunesButtonMetaData,
             linkBarMetaData,
             onlineClockMetaData,
             pageGroupMetaData,
             pageMetaData,
             groupMetaData,
             flashComponentMetaData,
             pagesContainerMetaData,
             payPalButtonMetaData,
             pinItPinWidgetMetaData,
             pinterestFollowMetaData,
             pinterestPinItMetaData,
             rssButtonMetaData,
             screenWidthContainerMetaData,
             stripContainerMetaData,
             singleAudioPlayerMetaData,
             siteButtonMetaData,
             siteSegmentContainerMetaData,
             siteStructureMetaData,
             skypeCallButtonMetaData,
             slideShowGalleryMetaData,
             thumbnailsMetaData,
             accordionMetaData,
             googleMapMetaData,
             spotifyFollowMetaData,
             subscribeFormMetaData,
             svgShapeMetaData,
             tinyMenuMetaData,
             backToTopButtonMetaData,
             verticalLineMetaData,
             vKShareButtonMetaData,
             weatherMetaData,
             wFacebookCommentMetaData,
             disqusCommentsMetaData,
             radioGroupMetaData,
             wGooglePlusOneMetaData,
             wPhotoMetaData,
             wTwitterFollowMetaData,
             wTwitterTweetMetaData,
             youTubeSubscribeButtonMetaData,
             tpaWidgetMetaData,
             tpaGluedWidgetMetaData,
             tpaSectionMetaData,
             appPageMetaData,
             appPartMetaData,
             appPart2MetaData,
             anchorMetaData,
             masonryMetaData,
             freestyleMetaData,
             stripGallerySlideShowMetaData,
             stripShowCaseMetaData,
             collageMetaData,
             threeDCarouselMetaData,
             videoMetaData,
             matrixGallery,
             documentMedia,
             spotifyPlayer,
             soundCloudMetaData,
             wRichTextMetaData,
             verticalMenuMetaData,
             dropDownMenuMetaData,
             sliderGalleryMetaData,
             PaginatedGridGalleryMetaData,
             containerMetaData,
             popupContainerMetaData,
             audioPlayerMetaData,
             clipArtMetaData,
             boxSlideShowSlideMetaData,
             boxSlideShowMetaData,
             stripSlideShowSlideMetaData,
             stripSlideShowMetaData,
             stripColumnsMetaData,
             textInputMetadata,
             checkboxMetadata,
             datePickerMetadata,
             columnMetadata,
             controllerMetaData,
             wixappsOnlyMetaData,
             hoverboxMetaData,
             gridMetaData
) {
    'use strict';

    var metaDataMap = {
        'wysiwyg.viewer.components.HeaderContainer': headerMetaData,
        'wysiwyg.viewer.components.EbayItemsBySeller': ebayItemsBySellerMetaData,
        'wysiwyg.viewer.components.FooterContainer': footerMetaData,
        'wysiwyg.viewer.components.AdminLoginButton': adminLoginButtonMetaData,
        'wysiwyg.viewer.components.BgImageStrip': bgImageStripMetaData,
        'wysiwyg.viewer.components.ContactForm': contactFormMetaData,
        'wysiwyg.common.components.facebooklikebox.viewer.FacebookLikeBox': facebookLikeBoxMetaData,
        'wysiwyg.viewer.components.WFacebookLike': facebookLikeMetaData,
        'wysiwyg.viewer.components.FacebookShare': facebookShareMetaData,
        'wysiwyg.viewer.components.FiveGridLine': fiveGridLineMetaData,
        'wysiwyg.viewer.components.FlickrBadgeWidget': flickrBadgeWidgetMetaData,
        'wysiwyg.common.components.imagebutton.viewer.ImageButton': imageButtonMetaData,
        'wysiwyg.viewer.components.ItunesButton': itunesButtonMetaData,
        'wysiwyg.viewer.components.LinkBar': linkBarMetaData,
        'wysiwyg.common.components.onlineclock.viewer.OnlineClock': onlineClockMetaData,
        'wysiwyg.viewer.components.PageGroup': pageGroupMetaData,
        'mobile.core.components.Page': pageMetaData,
        'wysiwyg.viewer.components.Group': groupMetaData,
        'wysiwyg.viewer.components.FlashComponent': flashComponentMetaData,
        'wysiwyg.viewer.components.PagesContainer': pagesContainerMetaData,
        'wysiwyg.viewer.components.PayPalButton': payPalButtonMetaData,
        'wysiwyg.common.components.pinitpinwidget.viewer.PinItPinWidget': pinItPinWidgetMetaData,
        'wysiwyg.viewer.components.PinterestFollow': pinterestFollowMetaData,
        'wysiwyg.common.components.pinterestpinit.viewer.PinterestPinIt': pinterestPinItMetaData,
        'wysiwyg.common.components.rssbutton.viewer.RSSButton': rssButtonMetaData,
        'wysiwyg.viewer.components.ScreenWidthContainer': screenWidthContainerMetaData,
        'wysiwyg.viewer.components.StripContainer': stripContainerMetaData,
        'wysiwyg.common.components.singleaudioplayer.viewer.SingleAudioPlayer': singleAudioPlayerMetaData,
        'wysiwyg.viewer.components.SiteButton': siteButtonMetaData,
        'wysiwyg.viewer.components.SiteSegmentContainer': siteSegmentContainerMetaData,
        'wysiwyg.viewer.components.WSiteStructure': siteStructureMetaData,
        'wysiwyg.common.components.skypecallbutton.viewer.SkypeCallButton': skypeCallButtonMetaData,
        'wysiwyg.viewer.components.SlideShowGallery': slideShowGalleryMetaData,
        'tpa.viewer.components.Thumbnails': thumbnailsMetaData,
        'tpa.viewer.components.Accordion': accordionMetaData,
        'wysiwyg.viewer.components.GoogleMap': googleMapMetaData,
        'wysiwyg.common.components.spotifyfollow.viewer.SpotifyFollow': spotifyFollowMetaData,
        'wysiwyg.common.components.subscribeform.viewer.SubscribeForm': subscribeFormMetaData,
        'wysiwyg.viewer.components.svgshape.SvgShape': svgShapeMetaData,
        'wysiwyg.viewer.components.mobile.TinyMenu': tinyMenuMetaData,
        'wysiwyg.common.components.backtotopbutton.viewer.BackToTopButton': backToTopButtonMetaData,
        'wysiwyg.viewer.components.VerticalLine': verticalLineMetaData,
        'wysiwyg.viewer.components.VKShareButton': vKShareButtonMetaData,
        'wysiwyg.common.components.weather.viewer.Weather': weatherMetaData,
        'wysiwyg.viewer.components.WFacebookComment': wFacebookCommentMetaData,
        'wysiwyg.common.components.disquscomments.viewer.DisqusComments': disqusCommentsMetaData,
        'wysiwyg.viewer.components.WGooglePlusOne': wGooglePlusOneMetaData,
        'wysiwyg.viewer.components.WPhoto': wPhotoMetaData,
        'wysiwyg.viewer.components.ClipArt': clipArtMetaData,
        'wysiwyg.viewer.components.WTwitterFollow': wTwitterFollowMetaData,
        'wysiwyg.viewer.components.WTwitterTweet': wTwitterTweetMetaData,
        'wysiwyg.common.components.youtubesubscribebutton.viewer.YouTubeSubscribeButton': youTubeSubscribeButtonMetaData,
        'wysiwyg.viewer.components.tpapps.TPAWidget': tpaWidgetMetaData,
        'wysiwyg.viewer.components.tpapps.TPASection': tpaSectionMetaData,
        'wysiwyg.viewer.components.tpapps.TPAGluedWidget': tpaGluedWidgetMetaData,
        'wysiwyg.viewer.components.tpapps.TPAMultiSection': tpaSectionMetaData,
        'wixapps.integration.components.AppPage': appPageMetaData,
        'wixapps.integration.components.AppPart': appPartMetaData,
        'wixapps.integration.components.AppPart2': appPart2MetaData,
        'wysiwyg.common.components.anchor.viewer.Anchor': anchorMetaData,
        'tpa.viewer.components.StripSlideshow': stripGallerySlideShowMetaData,
        'tpa.viewer.components.StripShowcase': stripShowCaseMetaData,
        'tpa.viewer.components.Collage': collageMetaData,
        'tpa.viewer.components.Masonry': masonryMetaData,
        'tpa.viewer.components.Freestyle': freestyleMetaData,
        'wysiwyg.viewer.components.tpapps.TPA3DCarousel': threeDCarouselMetaData,
        'wysiwyg.viewer.components.Video': videoMetaData,
        'wysiwyg.viewer.components.MatrixGallery': matrixGallery,
        'wysiwyg.viewer.components.documentmedia.DocumentMedia': documentMedia,
        'wysiwyg.common.components.spotifyplayer.viewer.SpotifyPlayer': spotifyPlayer,
        'wysiwyg.viewer.components.SoundCloudWidget': soundCloudMetaData,
        'wysiwyg.viewer.components.WRichText': wRichTextMetaData,
        'wysiwyg.common.components.verticalmenu.viewer.VerticalMenu': verticalMenuMetaData,
        'wysiwyg.viewer.components.menus.DropDownMenu': dropDownMenuMetaData,
        'wysiwyg.viewer.components.SliderGallery': sliderGalleryMetaData,
        'wysiwyg.viewer.components.PaginatedGridGallery': PaginatedGridGalleryMetaData,
        'mobile.core.components.Container': containerMetaData,
        'wysiwyg.viewer.components.PopupContainer': popupContainerMetaData,
        'wysiwyg.viewer.components.PopupCloseTextButton': siteButtonMetaData,
        'wysiwyg.viewer.components.AudioPlayer': audioPlayerMetaData,
        'wysiwyg.viewer.components.BoxSlideShowSlide': boxSlideShowSlideMetaData,
        'wysiwyg.viewer.components.BoxSlideShow': boxSlideShowMetaData,
        'wysiwyg.viewer.components.StripContainerSlideShowSlide': stripSlideShowSlideMetaData,
        'wysiwyg.viewer.components.StripContainerSlideShow': stripSlideShowMetaData,
        'wysiwyg.viewer.components.StripColumnsContainer': stripColumnsMetaData,
        'wysiwyg.common.components.verticalanchorsmenu.viewer.VerticalAnchorsMenu': verticalAnchorsMenuMetaData,
        'wysiwyg.viewer.components.inputs.TextInput': textInputMetadata,
        'wysiwyg.viewer.components.inputs.ComboBoxInput': textInputMetadata,
        'wysiwyg.viewer.components.inputs.Checkbox': checkboxMetadata,
        'wysiwyg.viewer.components.inputs.DatePicker': datePickerMetadata,
        'wysiwyg.viewer.components.Column': columnMetadata,
        'platform.components.AppController': controllerMetaData,
        'wysiwyg.viewer.components.ImageButtonWithText' : wixappsOnlyMetaData,
        'wysiwyg.viewer.components.inputs.RadioButton' : textInputMetadata,
        'wysiwyg.viewer.components.HoverBox' : hoverboxMetaData,
        'wysiwyg.viewer.components.inputs.RadioGroup' : radioGroupMetaData,
        'wysiwyg.viewer.components.Grid': gridMetaData
    };

    return {
        getMap: function () {
            return metaDataMap;
        }
    };
});
