define([
    'loggingUtils',
    'coreUtils',
    'dataFixer',
    'siteUtils',
    'translationsUtils',
    'wixUrlParser',
    'utils/fonts/uploadedFontsUtils',
    'utils/fonts/renderedFontsList',
    'utils/fonts/constants',
    'utils/fonts/fontsParser',
    'utils/mixins/timersMixins',
    'utils/mixins/postMessageCompMixin',
    'utils/svgFilters/svgFilters',
    'utils/svgShapes/svgFeatureDetection',
    'utils/socialAPI/socialAPI',
    'utils/widgets/widgetModel',
    'utils/integrations/fullStory',
    'imageClientApi',
    'utils/media/media',
    'utils/siteUtils/countryCodes',
    'utils/bi/wixappsClassicsLogger'
], function (loggingUtils,
             coreUtils,
             dataFixer,
             siteUtils,
             translationsUtils,
             wixUrlParser,
             uploadedFontsUtils,
             renderedFontsList,
             fontsConstants,
             fontsParser,
             timerMixins,
             postMessageCompMixin,
             svgFilters,
             svgFeatureDetection,
             socialAPI,
             widgetModel,
             fullStory,
             imageClientApi,
             media,
             countryCodes,
             wixappsClassicsLogger
) {
    'use strict';

    /**
     * @exports utils
     */
    var exports = {
        logger: loggingUtils.logger,
        log: loggingUtils.log,
        deprecatedSiteModelMigrater: dataFixer.deprecatedSiteModelMigrater,
        htmlTransformer: coreUtils.htmlTransformer,
        textSecurityFixer: coreUtils.textSecurityFixer,
        htmlParser: coreUtils.htmlParser,
        throttleUtils: coreUtils.throttleUtils,
        keyboardUtils: coreUtils.keyboardUtils,
        classNames: coreUtils.classNames,
        cookieUtils: coreUtils.cookieUtils,
        imageUtils: coreUtils.imageUtils,
        dataFixer: dataFixer,
        tween: coreUtils.tween,
        urlUtils: coreUtils.urlUtils,
        routersBackEndRequests: coreUtils.routersBackEndRequests,
        Store: coreUtils.Store,
        mobileViewportFixer: coreUtils.mobileViewportFixer,
        dataUtils: coreUtils.dataUtils,
        dateTimeUtils: coreUtils.dateTimeUtils,
        validationUtils: coreUtils.validationUtils,
        ajaxLibrary: coreUtils.ajaxLibrary,
        menuUtils: siteUtils.menuUtils,
        cssUtils: coreUtils.cssUtils,
        compFactory: siteUtils.compFactory,
        linkRenderer: siteUtils.linkRenderer,
        fonts: {
            uploadedFontsUtils: uploadedFontsUtils,
            renderedFontsList: renderedFontsList,
            constants: fontsConstants,
            fontsParser: fontsParser
        },
        wixUrlParser: wixUrlParser,
        wixUserApi: coreUtils.wixUserApi,
        MobileDeviceAnalyzer: siteUtils.MobileDeviceAnalyzer,
        browserDetection: siteUtils.browserDetection,
        SiteData: siteUtils.SiteData,
        pageRequests: siteUtils.pageRequests,
        hashUtils: coreUtils.hashUtils,
        textTransforms: coreUtils.textTransforms,
        guidUtils: coreUtils.guidUtils,
        arrayUtils: coreUtils.arrayUtils,
        stringUtils: coreUtils.stringUtils,
        countryCodes: countryCodes,
        mediaZoomCalculations: coreUtils.mediaZoomCalculations,
        objectUtils: coreUtils.objectUtils,
        animationFrame: coreUtils.animationFrame,
        scrollAnchors: coreUtils.scrollAnchors,
        layoutAnchors: siteUtils.layoutAnchors,
        originalValuesMapGenerator: siteUtils.originalValuesMapGenerator,
        domMeasurements: coreUtils.domMeasurements,
        storage: coreUtils.storage,
        style: coreUtils.style,
        galleriesCommonLayout: coreUtils.galleriesCommonLayout,
        requestsUtil: coreUtils.requestsUtil,
        migrateBgDataItem: dataFixer.fixBackgroundData.migrateBgDataItem,
        migrateBgString: dataFixer.fixBackgroundData.migrateBgString,
        imageTransformDataFixers: dataFixer.imageTransformDataFixers,
        timerMixins: timerMixins,
        boundingLayout: coreUtils.boundingLayout,
        siteConstants: coreUtils.siteConstants,
        languages: coreUtils.languages,
        componentsAnchorsMetaData: siteUtils.componentsAnchorsMetaData,
        verticalMenuCalculations: coreUtils.verticalMenuCalculations,
        nonPageItemZoom: coreUtils.nonPageItemZoom,
        appPartMediaInnerViewNameUtils: coreUtils.appPartMediaInnerViewNameUtils,
        translations: translationsUtils,
        anchorCyclesHelper: dataFixer.anchorCyclesHelper,
        postMessageCompMixin: postMessageCompMixin,
        colorParser: coreUtils.colorParser,
        reactComponentUtils: coreUtils.reactComponentUtils,
        dockUtils: coreUtils.dockUtils,
        layout: siteUtils.layout,
        positionAndSize: siteUtils.positionAndSize,
        viewportUtils: coreUtils.viewportUtils,
        containerBackgroundUtils: coreUtils.containerBackgroundUtils,
        svgFilters: svgFilters,
        svgFeatureDetection: svgFeatureDetection,
        math: coreUtils.math,
        socialAPI: socialAPI,
        functionUtils: coreUtils.functionUtils,
        constants: siteUtils.constants,
        siteRenderPrivateStuff: {
            fullToDisplayedJson: siteUtils.fullToDisplayedJson
        },
        modes: siteUtils.modes,
        structureDimensions: siteUtils.structureDimensions,
        performance: loggingUtils.performance,
        newrelic: loggingUtils.newrelic,
        balataConsts: coreUtils.balataConsts,
        blogAppPartNames: coreUtils.blogAppPartNames,
        widgetModel: widgetModel,
        integrations: {
            fullStory: fullStory
        },
        //TODO: remove when editor that points directly to imageClientApi is in prod.
        imageTransform: imageClientApi,
        socialShareHandler: siteUtils.socialShareHandler,
        media: media,
        socialCounterDatabaseAPI: siteUtils.socialCounterDatabaseAPI,
        errorPages: coreUtils.errorPages,
        logWixCodeConsoleMessage: coreUtils.logWixCodeConsoleMessage,
        wixappsClassicsLogger: wixappsClassicsLogger
    };
    return exports;
});
