export default {
	baseUrl: 'https://ecom.wix.com/',
	productsList: '_api/wix-ecommerce-renderer-web/store-manager/products/',
	orderList: '_api/wix-ecommerce-renderer-web/store-manager/orders/',
	collectionsList: '_api/wix-ecommerce-renderer-web/store-manager/categories',
	staticMediaUrl: 'https://static.wixstatic.com/media/',
	loginUrl: 'https://users.wix.com/_api/wix-html-login-webapp/auth/login',
	metasiteUrl: 'https://www.wix.com/_api/wix-dashboard-ng-webapp/metaSite',
	executeCatalogCommands: '_api/wix-ecommerce-renderer-web/store-manager/executeCatalogCommands',
	storeSettings: '_api/wix-ecommerce-renderer-web/store-manager/get-store-settings/all',
	markOrderAsPaidByStoreManager: '_api/wix-ecommerce-renderer-web/store-manager/order/MarkOrderAsPaidByStoreManager',
	markOrderAsReadByStoreManager: '_api/wix-ecommerce-renderer-web/store-manager/order/MarkOrderAsReadByStoreManager',
	changeShippingStatusByStoreManager: '_api/wix-ecommerce-renderer-web/store-manager/order/ChangeShippingStatusByStoreManager',
	productToCategory: '_api/wix-ecommerce-renderer-web/store-manager/catalog/AddProductToCategory',
	productFromCategory: '_api/wix-ecommerce-renderer-web/store-manager/catalog/RemoveProductFromCategory',
	createCart: '_api/wix-ecommerce-renderer-web/store-front/carts/create',
	createCartCommand: '_api/wix-ecommerce-renderer-web/store-front/cart/CreateCartCommand',
	addCartItems: '_api/wix-ecommerce-renderer-web/store-front/carts/executeBulk',
	addCartItemCommand: '_api/wix-ecommerce-renderer-web/store-front/cart/AddCartItemCommand',
	addCartItemsCommand: '_api/wix-ecommerce-renderer-web/store-front/cart/AddCartItemsCommand',
	setCartAdditionalPriceCommand: '_api/wix-ecommerce-renderer-web/store-front/cart/SetCartAdditionalPriceCommand',
	setMerchantDiscount: '_api/wix-ecommerce-renderer-web/mobile/cart/setMerchantDiscount',
	removeCartItemCommand: '_api/wix-ecommerce-renderer-web/store-front/cart/RemoveCartItemCommand',
	createOrder: '_api/wix-ecommerce-renderer-web/mobile/orders/createPosOrder',
	finishOrder: '_api/wix-ecommerce-renderer-web/mobile/orders/finishOrder',
	addBillingAddress: '_api/wix-ecommerce-renderer-web/store-manager/order/AddBillingAddress',
	sendNotificationAboutOrder: '_api/wix-ecommerce-renderer-web/mobile/orders/sendNotificationAboutOrder'
}