define(['lodash'], function (_) {
    'use strict';

    var defaultLayout = {width: 100, height: 100, x: 0, y: 0, scale: 1.0, rotationInDegrees: 0.0};
    var defaultImageDef = {uri: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQnv-4CsJ5Tpw4CPH3kZo2fJtq2oPLrd7JjDZwkjSNwDtpaUb_6_dKNPhju'};
    var defaultBackgroundDesignData = {
        background: {
            "type": "BackgroundMedia",
            "metaData": {"isPreset": false, "schemaVersion": "1.0", "isHidden": false},
            "color": "#242323",
            "colorOpacity": 1,
            "alignType": "center",
            "fittingType": "fill",
            "scrollType": "none",
            "colorOverlay": "",
            "colorOverlayOpacity": 0
        }
    };

    function getComponentDef(documentServices, defKey, overrides) {

        var componentsDef = {
            APP_CONTROLLER: {
                'skin': 'platform.components.skins.controllerSkin',
                'layout': {
                    'width': 40,
                    'height': 40,
                    'x': 20,
                    'y': 15,
                    'scale': 1,
                    'rotationInDegrees': 0,
                    'fixedPosition': false
                },
                'componentType': 'platform.components.AppController',
                'data': {
                    'type': 'AppController',
                    'applicationId': 'dataBinding',
                    'name': '',
                    'controllerType': 'dataset'
                }
            },
            WPHOTO: {
                layout: {
                    'width': 300,
                    'height': 200,
                    'x': 0,
                    'y': 0,
                    'scale': 1.0,
                    'rotationInDegrees': 0.0,
                    'anchors': []
                },
                'styleId': 'wp3',
                'skin': 'wysiwyg.viewer.skins.photo.RoundPhoto',
                'componentType': 'wysiwyg.viewer.components.WPhoto',
                data: _.merge(documentServices.data.createItem('Image'), defaultImageDef),
                props: documentServices.properties.createItem('WPhotoProperties')
            },
            CLIP_ART: {
                layout: defaultLayout,
                astyle: 'wp3',
                skin: 'wysiwyg.viewer.skins.photo.NoSkinPhoto',
                componentType: 'wysiwyg.viewer.components.ClipArt',
                data: _.merge(documentServices.data.createItem('Image'), defaultImageDef),
                props: documentServices.properties.createItem('WPhotoProperties')
            },
            POPUP: {
                'type': 'Page',
                'id': 'g13tp',
                'mobileComponents': [
                    {
                        'type': 'Container',
                        'id': 'comp-ili7dwo2',
                        'components': [],
                        'layout': {
                            'width': 302,
                            'height': 573,
                            'x': 9,
                            'y': 0,
                            'scale': 1,
                            'rotationInDegrees': 0,
                            'anchors': [],
                            'fixedPosition': false
                        },
                        'componentType': 'wysiwyg.viewer.components.PopupContainer',
                        'props': {
                            'type': 'PopupContainerProperties',
                            'metaData': {
                                'schemaVersion': '1.0',
                                'autoGenerated': true
                            },
                            'horizontalAlignment': 'center',
                            'verticalAlignment': 'center',
                            'alignmentType': 'nineGrid',
                            'horizontalOffset': 0,
                            'verticalOffset': 0,
                            'id': 'mobile_propItem-ili7dwo3'
                        },
                        'style': {
                            'type': 'TopLevelStyle',
                            'metaData': {
                                'isPreset': false,
                                'schemaVersion': '1.0',
                                'isHidden': false
                            },
                            'style': {
                                'properties': {
                                    'alpha-bg': '1',
                                    'bg': 'rgba(255,255,255,1)'
                                },
                                'propertiesSource': {
                                    'alpha-bg': 'value',
                                    'bg': 'value'
                                },
                                'groups': {}
                            },
                            'componentClassName': 'wysiwyg.viewer.components.PopupContainer',
                            'pageId': '',
                            'compId': '',
                            'styleType': 'custom',
                            'skin': 'wysiwyg.viewer.skins.stripContainer.DefaultStripContainer',
                            'id': 'style-ili7m0pe'
                        },
                        'design': {
                            'type': 'MediaContainerDesignData',
                            'metaData': {
                                'isPreset': false,
                                'schemaVersion': '1.0',
                                'isHidden': false
                            },
                            'background': {
                                'type': 'BackgroundMedia',
                                'metaData': {
                                    'isPreset': false,
                                    'schemaVersion': '1.0',
                                    'isHidden': false
                                },
                                'color': '#FFFFFE',
                                'colorOpacity': 1,
                                'alignType': 'center',
                                'fittingType': 'fill',
                                'scrollType': 'none',
                                'colorOverlay': '',
                                'colorOverlayOpacity': 0
                            },
                            'id': '#mobile_dataItem-ili7dwo4'
                        },
                        'skin': 'wysiwyg.viewer.skins.stripContainer.DefaultStripContainer'
                    }
                ],
                'skin': 'skins.core.InlineSkin',
                'layout': {
                    'width': 1440,
                    'height': 506,
                    'x': 0,
                    'y': 0,
                    'scale': 1,
                    'rotationInDegrees': 0,
                    'anchors': [],
                    'fixedPosition': false
                },
                'componentType': 'mobile.core.components.Page',
                'components': [
                    {
                        'type': 'Container',
                        'id': 'comp-ili7dwo2',
                        'skin': 'wysiwyg.viewer.skins.stripContainer.DefaultStripContainer',
                        'layout': {
                            'width': 600,
                            'height': 352,
                            'x': 190,
                            'y': 154,
                            'scale': 1,
                            'rotationInDegrees': 0,
                            'anchors': [],
                            'fixedPosition': false
                        },
                        'componentType': 'wysiwyg.viewer.components.PopupContainer',
                        'components': [],
                        'props': {
                            'type': 'PopupContainerProperties',
                            'metaData': {
                                'schemaVersion': '1.0'
                            },
                            'horizontalAlignment': 'center',
                            'verticalAlignment': 'center',
                            'alignmentType': 'nineGrid',
                            'horizontalOffset': 0,
                            'verticalOffset': 0,
                            'id': 'propItem-ili7dwo3'
                        },
                        'style': {
                            'type': 'TopLevelStyle',
                            'metaData': {
                                'isPreset': false,
                                'schemaVersion': '1.0',
                                'isHidden': false
                            },
                            'style': {
                                'properties': {
                                    'alpha-bg': '1',
                                    'bg': 'rgba(255,255,255,1)'
                                },
                                'propertiesSource': {
                                    'alpha-bg': 'value',
                                    'bg': 'value'
                                },
                                'groups': {}
                            },
                            'componentClassName': 'wysiwyg.viewer.components.PopupContainer',
                            'pageId': '',
                            'compId': '',
                            'styleType': 'custom',
                            'skin': 'wysiwyg.viewer.skins.stripContainer.DefaultStripContainer',
                            'id': 'style-ili7m0pe'
                        },
                        'design': {
                            'type': 'MediaContainerDesignData',
                            'metaData': {
                                'isPreset': false,
                                'schemaVersion': '1.0',
                                'isHidden': false
                            },
                            'background': {
                                'type': 'BackgroundMedia',
                                'metaData': {
                                    'isPreset': false,
                                    'schemaVersion': '1.0',
                                    'isHidden': false
                                },
                                'color': '#FFFFFE',
                                'colorOpacity': 1,
                                'alignType': 'center',
                                'fittingType': 'fill',
                                'scrollType': 'none',
                                'colorOverlay': '',
                                'colorOverlayOpacity': 0
                            },
                            'id': '#dataItem-ili7dwo4'
                        },
                        'mobileStructure': {
                            'type': 'Container',
                            'skin': 'wysiwyg.viewer.skins.stripContainer.DefaultStripContainer',
                            'layout': {
                                'width': 302,
                                'height': 573,
                                'x': 9,
                                'y': 0,
                                'scale': 1,
                                'rotationInDegrees': 0,
                                'anchors': [
                                    {
                                        'distance': 0,
                                        'originalValue': 481,
                                        'type': 'BOTTOM_PARENT',
                                        'locked': true,
                                        'targetComponent': 'g13tp'
                                    }
                                ],
                                'fixedPosition': false
                            },
                            'componentType': 'wysiwyg.viewer.components.PopupContainer',
                            'props': {
                                'type': 'PopupContainerProperties',
                                'metaData': {
                                    'schemaVersion': '1.0',
                                    'autoGenerated': true
                                },
                                'horizontalAlignment': 'center',
                                'verticalAlignment': 'center',
                                'alignmentType': 'nineGrid',
                                'horizontalOffset': 0,
                                'verticalOffset': 0
                            },
                            'style': {
                                'type': 'TopLevelStyle',
                                'metaData': {
                                    'isPreset': false,
                                    'schemaVersion': '1.0',
                                    'isHidden': false
                                },
                                'style': {
                                    'properties': {
                                        'alpha-bg': '1',
                                        'bg': 'rgba(255,255,255,1)'
                                    },
                                    'propertiesSource': {
                                        'alpha-bg': 'value',
                                        'bg': 'value'
                                    },
                                    'groups': {}
                                },
                                'componentClassName': 'wysiwyg.viewer.components.PopupContainer',
                                'pageId': '',
                                'compId': '',
                                'styleType': 'custom',
                                'skin': 'wysiwyg.viewer.skins.stripContainer.DefaultStripContainer'
                            },
                            'design': {
                                'type': 'MediaContainerDesignData',
                                'metaData': {
                                    'isPreset': false,
                                    'schemaVersion': '1.0',
                                    'isHidden': false
                                },
                                'background': {
                                    'type': 'BackgroundMedia',
                                    'metaData': {
                                        'isPreset': false,
                                        'schemaVersion': '1.0',
                                        'isHidden': false
                                    },
                                    'color': '#FFFFFE',
                                    'colorOpacity': 1,
                                    'alignType': 'center',
                                    'fittingType': 'fill',
                                    'scrollType': 'none',
                                    'colorOverlay': '',
                                    'colorOverlayOpacity': 0
                                }
                            }
                        }
                    }
                ],
                'data': {
                    'type': 'Page',
                    'metaData': {
                        'isPreset': false,
                        'schemaVersion': '1.0',
                        'isHidden': false
                    },
                    'title': 'Test Popup',
                    'hideTitle': true,
                    'icon': '',
                    'descriptionSEO': '',
                    'metaKeywordsSEO': '',
                    'pageTitleSEO': '',
                    'hidePage': false,
                    'underConstruction': false,
                    'tpaApplicationId': 0,
                    'pageSecurity': {
                        'requireLogin': false,
                        'passwordDigest': '',
                        'dialogLanguage': ''
                    },
                    'isPopup': true,
                    'indexable': true,
                    'isLandingPage': false,
                    'pageBackgrounds': {
                        'desktop': {
                            'ref': {
                                'type': 'BackgroundMedia',
                                'metaData': {
                                    'isPreset': false,
                                    'schemaVersion': '1.0',
                                    'isHidden': false
                                },
                                'color': '#000000',
                                'colorOpacity': 0.83,
                                'alignType': 'center',
                                'fittingType': 'fill',
                                'scrollType': 'none',
                                'colorOverlay': '',
                                'colorOverlayOpacity': 0
                            }
                        },
                        'mobile': {
                            'custom': true,
                            'ref': {
                                'type': 'BackgroundMedia',
                                'metaData': {
                                    'isPreset': false,
                                    'schemaVersion': '1.0',
                                    'isHidden': false
                                },
                                'color': '{color_16}',
                                'colorOpacity': 0.2,
                                'alignType': 'top',
                                'fittingType': 'fill',
                                'scrollType': 'fixed'
                            },
                            'isPreset': true
                        }
                    }
                },
                'props': {
                    'type': 'PageProperties',
                    'metaData': {
                        'schemaVersion': '1.0'
                    },
                    'mobile': {
                        'popup': {
                            'closeOnOverlayClick': true
                        }
                    },
                    'desktop': {
                        'popup': {
                            'closeOnOverlayClick': true
                        }
                    },
                    'id': 'g13tp'
                },
                'style': 'p1'
            },
            POPUP_CLOSE_TEXT_BUTTON: {
                'type': 'Component',
                'skin': 'wysiwyg.viewer.skins.button.BasicButton',
                'layout': {
                    'width': 142,
                    'height': 40,
                    'x': 10,
                    'y': 15,
                    'scale': 1,
                    'rotationInDegrees': 0,
                    'fixedPosition': false
                },
                'componentType': 'wysiwyg.viewer.components.PopupCloseTextButton',
                'data': {
                    'type': 'LinkableButton',
                    'metaData': {'isPreset': false, 'schemaVersion': '1.0', 'isHidden': false},
                    'label': 'Take Me There!'
                },
                'props': {
                    'type': 'ButtonProperties',
                    'metaData': {'schemaVersion': '1.0'},
                    'align': 'center',
                    'margin': 0
                },
                'style': {
                    'type': 'TopLevelStyle',
                    'metaData': {'isPreset': false, 'schemaVersion': '1.0', 'isHidden': false},
                    'style': {
                        'groups': {},
                        'properties': {
                            'alpha-bg': '1',
                            'alpha-bgh': '1',
                            'alpha-brd': '1',
                            'alpha-brdh': '1',
                            'alpha-txt': '1',
                            'alpha-txth': '1',
                            'bg': '#3D9BE9',
                            'bgh': '#2B689C',
                            'boxShadowToggleOn-shd': 'false',
                            'brd': '#2B689C',
                            'brdh': '#3D9BE9',
                            'brw': '0px',
                            'fnt': 'normal normal normal 14px/1.4em avenir-lt-w01_35-light1475496',
                            'rd': '20px',
                            'shd': '0 1px 4px rgba(0, 0, 0, 0.6);',
                            'txt': '#FFFFFF',
                            'txth': '#FFFFFF'
                        },
                        'propertiesSource': {
                            'bg': 'value',
                            'bgh': 'value',
                            'brd': 'value',
                            'brdh': 'value',
                            'brw': 'value',
                            'fnt': 'value',
                            'rd': 'value',
                            'shd': 'value',
                            'txt': 'value',
                            'txth': 'value'
                        }
                    },
                    'componentClassName': 'wysiwyg.viewer.components.PopupCloseTextButton',
                    'pageId': '',
                    'compId': '',
                    'styleType': 'custom',
                    'skin': 'wysiwyg.viewer.skins.button.BasicButton'
                }
            },
            POPUP_CLOSE_ICON_BUTTON: {
                'type': 'Component',
                'skin': 'svgshape.v2.Svg_9a8686831e874878a55a90925c0feb6c',
                'layout': {
                    'width': 35,
                    'height': 35,
                    'x': 8,
                    'y': 15,
                    'scale': 1,
                    'rotationInDegrees': 0,
                    'fixedPosition': false
                },
                'componentType': 'wysiwyg.viewer.components.PopupCloseIconButton',
                'data': {
                    'type': 'SvgShape',
                    'metaData': {
                        'isPreset': false,
                        'schemaVersion': '1.0',
                        'isHidden': false
                    }
                },
                'props': {
                    'type': 'SvgShapeProperties',
                    'metaData': {
                        'schemaVersion': '1.0'
                    },
                    'maintainAspectRatio': true
                },
                'style': {
                    'type': 'TopLevelStyle',
                    'metaData': {
                        'isPreset': false,
                        'schemaVersion': '1.0',
                        'isHidden': false
                    },
                    'style': {
                        'groups': {},
                        'properties': {
                            'alpha-fillcolor': '1',
                            'alpha-stroke': '1',
                            'fillcolor': '#000000',
                            'stroke': '#ED1566',
                            'strokewidth': '0px'
                        },
                        'propertiesSource': {
                            'fillcolor': 'value',
                            'stroke': 'value',
                            'strokewidth': 'value'
                        }
                    },
                    'componentClassName': 'wysiwyg.viewer.components.PopupCloseIconButton',
                    'pageId': '',
                    'compId': '',
                    'styleType': 'custom',
                    'skin': 'svgshape.v2.Svg_9a8686831e874878a55a90925c0feb6c'
                }
            },
            CONTAINER: {
                'layout': {
                    'width': 500,
                    'height': 500,
                    'x': 10,
                    'y': 10,
                    'rotationInDegrees': 0,
                    'fixedPosition': false,
                    'scale': 1
                },
                'type': 'Container',
                'skin': 'wysiwyg.viewer.skins.area.RoundArea',
                'componentType': 'mobile.core.components.Container',
                'components': []
            },
            LINE: {
                layout: defaultLayout,
                skin: 'wysiwyg.viewer.skins.line.SolidLine',
                componentType: 'wysiwyg.viewer.components.FiveGridLine',
                props: documentServices.properties.createItem('FiveGridLineProperties')
            },
            VKSHARE: {
                layout: defaultLayout,
                type: 'VKShareButton',
                skin: 'skins.viewer.vkshare.VKShareSkin',
                componentType: 'wysiwyg.viewer.components.VKShareButton',
                data: documentServices.data.createItem('VKShareButton'),
                props: documentServices.properties.createItem('VKShareProperties')
            },
            SLIDESHOW: {
                type: 'Gallery',
                skin: 'wysiwyg.viewer.skins.gallery.SlideShowTextOverlay',
                componentType: 'wysiwyg.viewer.components.SlideShowGallery',
                data: documentServices.data.createItem('ImageList'),
                props: documentServices.properties.createItem('SlideShowGalleryProperties')
            },
            FACEBOOKLIKE: {
                type: 'FacebookLike',
                skin: 'skins.core.FacebookLikeSkin',
                componentType: 'wysiwyg.viewer.components.WFacebookLike',
                props: documentServices.properties.createItem('WFacebookLikeProperties')
            },
            BG_IMAGE_STRIP: {
                'layout': {
                    'width': 300,
                    'height': 200,
                    'x': 0,
                    'y': 0,
                    'scale': 1.0,
                    'rotationInDegrees': 0.0,
                    'anchors': []
                },
                'astyle': 'wp3',
                'skin': 'skins.viewer.bgimagestrip.BgImageStripSkin',
                'componentType': 'wysiwyg.viewer.components.BgImageStrip',
                props: documentServices.properties.createItem('BgImageStripUnifiedProperties')
            },
            STRIP_COLUMNS_CONTAINER: {
                "layout": {
                    "width": 980,
                    "height": 200,
                    "x": 0,
                    "y": 0,
                    "scale": 1.0,
                    "rotationInDegrees": 0.0,
                    "anchors": []
                },
                "components": [],
                "styleId": "strc1",
                "skin": "wysiwyg.viewer.skins.stripContainer.DefaultStripContainer",
                "componentType": "wysiwyg.viewer.components.StripColumnsContainer",
                props: documentServices.properties.createItem("StripColumnsContainerProperties"),
                design: _.merge(documentServices.design.createItem("MediaContainerDesignData"), defaultBackgroundDesignData)
            },
            WRICH_TEXT: {
                'componentType': 'wysiwyg.viewer.components.WRichText',
                'type': 'Component',
                'id': 'WRchTxt1-6wd',
                'styleId': 'txtNew',
                'skin': 'wysiwyg.viewer.skins.WRichTextNewSkin',
                'layout': {
                    'x': 25,
                    'y': 22,
                    'width': 450,
                    'height': 5
                },
                'data': {
                    'type': 'StyledText',
                    'metaData': {
                        'isPreset': false,
                        'schemaVersion': '1.0',
                        'isHidden': false
                    },
                    'text': '<p class=\'font_8\'><span style=\'font-size:30px;\'><span style=\'font-family:open sans;\'><span class=\'color_15\'>footerTxt1</span></span></span></p>\n<p class=\'font_8\'><span style=\'font-size:30px;\'><span style=\'font-family:open sans;\'><span class=\'color_15\'>footerTxt2</span></span></span></p>',
                    'stylesMapId': 'CK_EDITOR_PARAGRAPH_STYLES'
                },
                'dataRefs': {},
                'dataId': 'cewt'
            },
            SITE_BUTTON: {
                'type': 'Component',
                'skin': 'wysiwyg.viewer.skins.button.BasicButton',
                'layout': {
                    'width': 142,
                    'height': 40,
                    'x': 20,
                    'y': 15,
                    'scale': 1,
                    'rotationInDegrees': 0,
                    'fixedPosition': false
                },
                'componentType': 'wysiwyg.viewer.components.SiteButton',
                'data': {
                    'type': 'LinkableButton',
                    'metaData': {'isPreset': false, 'schemaVersion': '1.0', 'isHidden': false},
                    'label': 'Kontakt',
                    'link': null
                },
                'props': {
                    'type': 'ButtonProperties',
                    'metaData': {'schemaVersion': '1.0'},
                    'align': 'center',
                    'margin': 0
                },
                'style': {
                    'type': 'TopLevelStyle',
                    'metaData': {'isPreset': false, 'schemaVersion': '1.0', 'isHidden': false},
                    'style': {
                        'groups': {},
                        'properties': {
                            'alpha-bg': '1',
                            'alpha-bgh': '1',
                            'alpha-brd': '1',
                            'alpha-brdh': '1',
                            'alpha-txt': '1',
                            'alpha-txth': '1',
                            'bg': '#3D9BE9',
                            'bgh': '#2B689C',
                            'boxShadowToggleOn-shd': 'false',
                            'brd': '#2B689C',
                            'brdh': '#3D9BE9',
                            'brw': '0px',
                            'fnt': 'normal normal normal 14px/1.4em raleway',
                            'rd': '20px',
                            'shd': '0 1px 4px rgba(0, 0, 0, 0.6);',
                            'txt': '#FFFFFF',
                            'txth': '#FFFFFF'
                        },
                        'propertiesSource': {
                            'bg': 'value',
                            'bgh': 'value',
                            'brd': 'value',
                            'brdh': 'value',
                            'brw': 'value',
                            'fnt': 'value',
                            'rd': 'value',
                            'shd': 'value',
                            'txt': 'value',
                            'txth': 'value'
                        }
                    },
                    'componentClassName': 'wysiwyg.viewer.components.SiteButton',
                    'pageId': '',
                    'compId': 'i6967q7w',
                    'styleType': 'custom',
                    'skin': 'wysiwyg.viewer.skins.button.BasicButton'
                }
            },
            HOVER_BOX: {
                'id': 'comp-hoverbox-id',
                'type': 'Container',
                'componentType': 'wysiwyg.viewer.components.HoverBox',
                'layout': {
                    'width': 608,
                    'height': 360,
                    'x': 0,
                    'y': 60,
                    'scale': 1,
                    'rotationInDegrees': 0,
                    'fixedPosition': false
                },
                'modes': {
                    'definitions': [{
                        'modeId': 'regular-mode-id',
                        'type': 'DEFAULT',
                        'label': 'MODE_LABEL_FROM_PRESET',
                        'params': ''
                    }, {
                        'modeId': 'hover-mode-id',
                        'type': 'HOVER',
                        'label': 'MODE_LABEL_FROM_PRESET',
                        'params': ''
                    }],
                    'overrides': []
                },
                'components': [],
                'style': {
                    'type': 'TopLevelStyle',
                    'style': {
                        'groups': {},
                        'properties': {
                            'alpha-bg': '1',
                            'alpha-brd': '1',
                            'bg': '206,224,193,1',
                            'boxShadowToggleOn-shd': 'false',
                            'brd': '#324158',
                            'brw': '0px',
                            'rd': '0px',
                            'shd': '0px 1px 4px 0px rgba(0,0,0,0.6)'
                        },
                        'propertiesSource': {
                            'bg': 'value',
                            'brd': 'value',
                            'brw': 'value',
                            'rd': 'value',
                            'shd': 'value'
                        }
                    },
                    'componentClassName': 'wysiwyg.viewer.components.HoverBox',
                    'pageId': '',
                    'compId': '',
                    'styleType': 'custom',
                    'skin': 'wysiwyg.viewer.skins.mediaContainer.DefaultMediaContainer'
                },
                'design': {
                    'type': 'MediaContainerDesignData',
                    'background': {
                        'type': 'BackgroundMedia',
                        'mediaRef': {
                            'type': 'Image',
                            'title': 'Freshly Made Truffles',
                            'uri': '8eb3c7e813d74673941130542c0c2ce1.jpg',
                            'description': 'public/491df47b-5958-4dc7-9029-37f428755d45/edfd0ae7-86e6-4adb-9332-7697307e9f1b',
                            'width': 2768,
                            'height': 1560,
                            'alt': '',
                            'artist': {
                                'id': '',
                                'name': ''
                            }
                        },
                        'color': '#FAFAEB',
                        'colorOpacity': 1,
                        'alignType': 'center',
                        'fittingType': 'fill',
                        'scrollType': 'none',
                        'colorOverlay': '#F4F5B8',
                        'colorOverlayOpacity': 0
                    }
                }
            },
            CONTAINER_WITH_MODES: {
                'id': 'containerWithModes',
                'type': 'Container',
                'componentType': 'mobile.core.components.Container',
                'layout': {
                    'width': 608,
                    'height': 360,
                    'x': 0,
                    'y': 60,
                    'scale': 1,
                    'rotationInDegrees': 0,
                    'fixedPosition': false
                },
                'modes': {
                    'definitions': [{
                        'modeId': 'regular-mode-id',
                        'type': 'DEFAULT',
                        'label': 'MODE_LABEL_FROM_PRESET',
                        'params': ''
                    }, {
                        'modeId': 'hover-mode-id',
                        'type': 'HOVER',
                        'label': 'MODE_LABEL_FROM_PRESET',
                        'params': ''
                    }],
                    'overrides': []
                },
                'components': [],
                'style': {
                    'type': 'TopLevelStyle',
                    'style': {
                        'groups': {},
                        'properties': {
                            'alpha-bg': '1',
                            'alpha-brd': '1',
                            'bg': '206,224,193,1',
                            'boxShadowToggleOn-shd': 'false',
                            'brd': '#324158',
                            'brw': '0px',
                            'rd': '0px',
                            'shd': '0px 1px 4px 0px rgba(0,0,0,0.6)'
                        },
                        'propertiesSource': {
                            'bg': 'value',
                            'brd': 'value',
                            'brw': 'value',
                            'rd': 'value',
                            'shd': 'value'
                        }
                    },
                    'componentClassName': 'wysiwyg.viewer.components.HoverBox',
                    'pageId': '',
                    'compId': '',
                    'styleType': 'custom',
                    'skin': 'wysiwyg.viewer.skins.mediaContainer.DefaultMediaContainer'
                },
                'design': {
                    'type': 'MediaContainerDesignData',
                    'background': {
                        'type': 'BackgroundMedia',
                        'mediaRef': {
                            'type': 'Image',
                            'title': 'Freshly Made Truffles',
                            'uri': '8eb3c7e813d74673941130542c0c2ce1.jpg',
                            'description': 'public/491df47b-5958-4dc7-9029-37f428755d45/edfd0ae7-86e6-4adb-9332-7697307e9f1b',
                            'width': 2768,
                            'height': 1560,
                            'alt': '',
                            'artist': {
                                'id': '',
                                'name': ''
                            }
                        },
                        'color': '#FAFAEB',
                        'colorOpacity': 1,
                        'alignType': 'center',
                        'fittingType': 'fill',
                        'scrollType': 'none',
                        'colorOverlay': '#F4F5B8',
                        'colorOverlayOpacity': 0
                    }
                }
            },
            ANCHOR: {
                "type": "Component",
                "skin": "wysiwyg.common.components.anchor.viewer.skins.AnchorSkin",
                "layout": {
                    "width": 1918,
                    "height": 21,
                    "x": -469,
                    "y": 332.5,
                    "scale": 1,
                    "rotationInDegrees": 0,
                    "fixedPosition": false
                },
                "componentType": "wysiwyg.common.components.anchor.viewer.Anchor",
                "data": {
                    "type": "Anchor",
                    "metaData": {
                        "isPreset": false,
                        "schemaVersion": "1.0",
                        "isHidden": false
                    },
                    "name": "Anchor 2",
                    "compId": "i5rzonck_3"
                },
                "style": "Anchor_1",
                "id": "i5rzonck_3"
            }
        };

        var compDef = componentsDef[defKey] || {};
        return _.merge(compDef, overrides);
    }

    function getDefaultImageDef() {
        return defaultImageDef;
    }

    function getComponentDomNode(siteDocument, compId, viewMode) {
        var mode = viewMode || 'DESKTOP';
        var id = mode === 'MOBILE' ? 'mobile_' + compId : compId;
        return siteDocument.getElementById(id);
    }

    function getSkinPartDomNode(siteDocument, compId, skinPartName) {
        var id = compId + skinPartName;
        return siteDocument.getElementById(id);
    }

    return {
        getComponentDef: getComponentDef,
        getDefaultImageDef: getDefaultImageDef,
        getComponentDomNode: getComponentDomNode,
        getSkinPartDomNode: getSkinPartDomNode
    };
});
