define([], function() {
    'use strict';

    return {
        UNKNOWN_SERVER_ERROR: 'UNKNOWN_SERVER_ERROR',
        HTTP_REQUEST_ERROR: 'HTTP_REQUEST_ERROR',

        SAVE_BLOCKED_BY_DOCUMENT_SERVICES: 'SAVE_BLOCKED_BY_DOCUMENT_SERVICES',
        NOT_LOGGED_IN: 'NOT_LOGGED_IN',
        USER_NOT_AUTHORIZED_FOR_SITE: 'USER_NOT_AUTHORIZED_FOR_SITE',

        CONCURRENT_SAVE: 'CONCURRENT_SAVE_ERROR',
        SITE_NAME_TAKEN: 'SITE_NAME_TAKEN_ERROR',
        DUPLICATE_COMPONENTS: 'DUPLICATE_COMPONENTS',
        DATA_REFERENCE_MISMATCH: 'DATA_REFERENCE_MISMATCH',
        MISSING_CONTAINERS: 'MISSING_CONTAINERS',
        SAVE_PUBLISH_DISABLED_ON_SERVER: 'SAVE_PUBLISH_DISABLED_ON_SERVER',
        CONCURRENT_AUTO_SAVE: 'CONCURRENT_AUTO_SAVE',
        SITE_STALE_STATE_FROM_AUTO_SAVE: 'SITE_STALE_STATE_FROM_AUTO_SAVE'
    };
});
